### PR TITLE
added postman documentation

### PR DESCRIPTION
**Pull request by Pragya2056**
The issue [write a documentation on APIs and Postman]( #11 ) was taken care of. 
SInce API post was previously made [here](https://github.com/GDSC-CEC/HacktoberFest-2022-Technical-Documentation/blob/main/ShaileshKumar007.md), I have made postman documentation and if you are still interested in another API documentation - please let me know.

### CODE REVIEW

**Comment by Pragya2056** [comment]
#11 - taken care of.

**Review by ShaileshKumar007 — CHANGES_REQUESTED** [review]
Thank you for your contribution.
Your contribution is great but it looks more like a blog and not like documentation. 
It would be great if you could add some more technical details.

**Comment by Pragya2056** [comment]
Sure I will make the corrections

**Comment by Pragya2056** [comment]
The changes have been made

**Review by ShaileshKumar007 — APPROVED** [review]
Your documentation looks good to me.
Thanks for your contribution

**Comment by Pragya2056** [comment]
Thank you!!

**Pull request merged**
